---
version: "3.7"

volumes:
  alexa-wol:
    name: alexa-wol

services:
  alexa:
    image: cristianeduardmihai/alexa-wol:latest
    container_name: Alexa-WOL
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Bucharest
    volumes:
      - alexa-wol:/alexa/api/config