name: Sync docker overview with README.md

on:
    push:
      branches:
        - "main"
      paths:
        - "README.md"
    
    workflow_dispatch:

jobs:
    sync:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@master
  
          - uses: meeDamian/sync-readme@v1.0.6
            with:
              user: cristianeduardmihai
              pass: ${{ secrets.DOCKERHUB_TOKEN }}
              slug: cristianeduardmihai/alexa-wol
              readme: ./README.md
              description: A Fauxmo frontend that facilitates multi-device control via Alexa services.